%The function generates a random m × n dimensional matrix A with approximate
%density d and singular values given by the non-negative input vector rc. 
%The number of non-zero singular values in rc is of course the desired rank r
%The matrix is generated by sprand using random plane rotations applied to a 
%diagonal matrix with the given singular values. The shape of this
%distribution is concave, and the entries are not extreme.


function A = genA(m,n,r,dens)

    M = 2;
    
    rho=(1/M)^(2/(r+1));
    
    rc=M*rho.^(1:r);
    
    A=sprand(m,n,dens,rc);
    
end

            